### ISSUE TITLE
Create archive of channel discussion

### ISSUE THREAD

**Issue by stevefaulkner** [w3c/a11ySlackers#1]
There is a gitter provided archive https://gitter.im/w3c/a11ySlackers/archives/2015/07/15 but the UI sucks, so want to get archive in form that is more usable for all. presuming Giiter API would be of help https://developer.gitter.im/docs/welcome. Also imprtant to have w3c repo of archives for posterity...

**Comment by ZoeBijl** [comment]
I can help with html/css, if someone else could handle JavaScript work.

**Comment by ZoeBijl** [comment]
This can be closed since we have daily archives now, no?
